# Python 3.9를 베이스 이미지로 사용
FROM python:3.9-slim

# 작업 디렉토리 설정
WORKDIR /app

# 의존성 파일 복사 및 설치
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
RUN apt-get update && apt-get install -y iproute2 && rm -rf /var/lib/apt/lists/*

# 소스 코드 복사
COPY . .

# Uvicorn 서버 실행
CMD ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "5000"]
