name: Multi-Service Deploy to GHCR

on:
  push:
    branches: [ "main" ] # 메인 브랜치에 푸시될 때 실행

env:
  REGISTRY: ghcr.io
  # GitHub 아이디를 소문자로 변환하여 사용해야 함
  IMAGE_NAME: ${{ github.repository_owner }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    # 각 서비스 리스트 정의
    strategy:
      matrix:
        service: [auth_server, employee_server, frontend, gateway, photo_service]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: LargeSsun
          password: ${{ secrets.GH_PAT }}

      - name: Build and Push Docker image
        uses: docker/build-push-action@v4
        with:
          # 각 서비스 폴더를 빌드 컨텍스트로 지정
          context: ./${{ matrix.service }}
          # Dockerfile 위치 지정
          file: ./${{ matrix.service }}/Dockerfile
          push: true
          # 태그 형식: ghcr.io/아이디/서비스명:latest
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/${{ matrix.service }}:latest
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/${{ matrix.service }}:${{ github.sha }}
